version: "3.8"

services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    image: shypple-technical-test:1.0.0
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached

  serve:
    <<: *app
    command: yarn serve
    ports:
      - "8080:8080"
